apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: ecommerce.local
    http:
      paths:
      - path: /products/?(.*)
        pathType: Prefix
        backend:
          service:
            name: product
            port:
              number: 8000
      - path: /users/?(.*)
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 8001
