apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: pjsweden2025/product-service:latest
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              value: ecommerce
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - port: 5000
      targetPort: 5000
