apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: pjsweden2025/user-service:latest   # update with your Docker Hub username
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              value: ecommerce
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
          ports:
            - containerPort: 8000   # matches your Dockerfile CMD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer   # or NodePort if your environment doesn’t support LoadBalancer
  selector:
    app: user-service
  ports:
    - port: 8000
      targetPort: 8000
