apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: your-dockerhub-username/product-service:1.0
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: ecommerce
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - port: 8001
      targetPort: 8001
